export default {
  projects: [
    {
      href: 'https://github.com/thebhushanmhatre/food-recipe-app',
      img: 'images/projects/recipe-app.jpg',
      description: ['React', 'Javascript', 'Fetch API'],
      name: 'Recipe App',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/bhushan-portfolio/blob/master/src/components/projects/RandomQuoteMachine.js',
      img: 'images/projects/quotes.jpg',
      description: ['Javascript'],
      name: 'Random Quote Machine',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/bhushan-portfolio/blob/master/src/components/projects/ToDoList.js',
      img: 'images/projects/todoapp.jpg',
      description: ['React', 'Javascript'],
      name: 'To Do List App',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/bhushan-portfolio/blob/master/src/components/projects/MarkdownPreviewer.js',
      img: 'images/projects/markdown.jpg',
      description: ['Javascript'],
      name: 'Markdown Previewer',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/bhushan-portfolio/blob/master/src/components/projects/PomodoroClock.js',
      img: 'images/projects/clock.jpg',
      description: ['Javascript'],
      name: 'Pomodoro Clock',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/book_flights',
      img: 'images/projects/bookflight.jpg',
      description: ['Ruby', 'Ruby on Rails'],
      name: 'Flight Booking App',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://codepen.io/thebhushanmhatre/full/BbPrwa',
      img: 'images/projects/calculator.jpg',
      description: ['Javascript'],
      name: 'Simple Calculator',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://codepen.io/thebhushanmhatre/full/QYeKBy',
      img: 'images/projects/drum.jpg',
      description: ['Javascript'],
      name: 'Drum Machine',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://codepen.io/thebhushanmhatre/full/KJbZrY',
      img: 'images/projects/bookmark.jpg',
      description: ['Javascript'],
      name: 'Bookmark App',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://codepen.io/thebhushanmhatre/full/aXPoNw',
      img: 'images/projects/weights.jpg',
      description: ['Javascript'],
      name: 'Intergallatic Weights',
      visible: true,
      target: '_blank',
    },
    {
      href: '',
      img: 'images/projects/senti.jpg',
      description: ['Python', 'Machine Learning'],
      name: 'Sentiment Analysis',
      visible: false,
      target: '',
    },
    {
      href: 'https://www.kaggle.com/thebhushanmhatre/my-firsttry-on-kaggle/',
      img: 'images/projects/titanic.jpg',
      description: ['Python', 'Machine Learning'],
      name: 'Kaggle: Titanic Dataset',
      visible: true,
      target: '_blank',
    },
    {
      href: '',
      img: 'images/projects/radar.jpg',
      description: ['Electronics'],
      name: 'Arduino Radar',
      visible: false,
      target: '_blank',
    },
    {
      href: '',
      img: 'images/projects/robarm.jpg',
      description: ['Electronics'],
      name: 'Haptic Robotic Arm',
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/Tetris',
      img: 'images/projects/tetris_js.jpg',
      description: ['JavaScript', 'Game'],
      name: 'Tetris Game',
      visible: true,
      target: '_blank',
    },
    {
      href: 'notebooks/WebScraping.html',
      img: 'images/projects/web_scrapping.jpg',
      description: ['Python', 'Web Scrapping'],
      name: 'Web Scrapping using Beautiful Soup',
      visible: true,
      target: '_blank',
    },
    {
      href: 'notebooks/Handwashing.html',
      img: 'images/projects/hand_washing.jpg',
      description: ['Python', 'Data Analysis'],
      name: 'Wash your Hands says the Data',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/url-shortener',
      img: 'images/projects/url_shortener.jpg',
      description: ['Python'],
      name: 'Url-Shortner',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/react-flask-app',
      img: 'images/projects/react_flask_app.jpg',
      description: ['Javascript', 'Python', 'React', 'Flask'],
      name: 'React-Flask App',
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://github.com/thebhushanmhatre/JSProjects',
      img: 'images/projects/js_apps.jpg',
      description: ['Javascript'],
      name: 'Vanilla Javascript Apps',
      visible: false,
      target: '_blank',
    },
  ],
  certificates: [
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/VTHK4VHWBLLP',
      img: '/images/certificates/express_server_mongodb.jpg',
      name: 'Server-side Development with NodeJS, Express and MongoDB',
      issuer: 'Coursera',
      institute: 'The Hong Kong University of Science and Technology',
      professor: 'Jogesh K. Muppala',
      description: ['Javascript', 'MongoDB', 'Express', 'API'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/B4LJHAVNG9B8',
      img: '/images/certificates/react_coursera_hongkong.jpg',
      name: 'Front-End Web Development with React',
      issuer: 'Coursera',
      institute: 'The Hong Kong University of Science and Technology',
      professor: 'Jogesh K. Muppala',
      description: ['Javascript', 'React', 'Redux'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/WXBNNV2ZFS9Y',
      img: '/images/certificates/bootstrap_coursera_hongkong.jpg',
      name: 'Front-End Web UI Frameworks and Tools: Bootstrap 4',
      issuer: 'Coursera',
      institute: 'The Hong Kong University of Science and Technology',
      professor: 'Jogesh K. Muppala',
      description: ['Javascript', 'Bootstrap'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/C969LNUBGSZN',
      img: '/images/certificates/js_interactivity_coursera.jpg',
      name: 'Interactivity with JavaScript',
      issuer: 'Coursera',
      institute: 'University of Michigan',
      professor: 'Kalmin Haznis',
      description: ['Javascript'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/V7JY5BJW7RZJ',
      img: '/images/certificates/ror_intro.jpg',
      name: 'Ruby on Rails: An Introduction',
      issuer: 'Coursera',
      institute: 'Johns Hopkins University',
      professor: 'Kalmin Haznis',
      description: ['Ruby', 'Ruby on Rails'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/ruby-on-rails-5-essential-training',
      img: '/images/certificates/ror_essential_linkedin.jpg',
      name: 'Ruby on Rails 5 Essential Training',
      issuer: 'Linkedin',
      professor: 'Kevin Skoglund',
      description: ['Ruby', 'Ruby on Rails'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/learning-sinatra',
      img: '/images/certificates/sinatra_linkedin.jpg',
      name: 'Learning Sinatra',
      issuer: 'Linkedin',
      professor: 'Kevin Skoglund',
      description: ['Ruby', 'Sinatra'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/learning-react-js-4',
      img: '/images/certificates/learning_reactJS_linkedin.jpg',
      name: 'Learning React.js',
      issuer: 'Linkedin',
      professor: 'Eve Porcello',
      description: ['Javascript', 'React'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/designing-restful-apis',
      img: '/images/certificates/designing_RESTful_APIs_linkedin.jpg',
      name: 'Designing Restful APIs',
      issuer: 'Linkedin',
      professor: 'Keith Casey',
      description: ['API'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/programming-foundations-databases-2',
      img: '/images/certificates/prog_foundations_database_linkedin.jpg',
      name: 'Programming Foundations Database',
      issuer: 'Linkedin',
      professor: 'Scott Simpson',
      description: ['SQL'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/game-development-foundations-game-related-math',
      img: '/images/certificates/game_dev_found_linkedin.jpg',
      name: 'JS Game Development Foundations',
      issuer: 'Linkedin',
      professor: 'Jesse Freeman',
      description: ['Javascript', 'Game'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.freecodecamp.org/certification/thebhushanmhatre/front-end-libraries',
      img: '/images/certificates/certi3fcc.jpg',
      name: 'Front End Libraries Developer Certification',
      issuer: 'FreeCodeCamp',
      professor: '',
      description: ['Javascript', 'React', 'Redux', 'Bootstrap'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.freecodecamp.org/certification/thebhushanmhatre/javascript-algorithms-and-data-structures',
      img: '/images/certificates/certi2fcc.jpg',
      name: 'JavaScript Algorithms and Data Structures Developer Certification',
      issuer: 'FreeCodeCamp',
      professor: '',
      description: ['Javascript'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.freecodecamp.org/certification/thebhushanmhatre/responsive-web-design',
      img: '/images/certificates/certi1fcc.jpg',
      name: 'Responsive Web Design Developer Certification',
      issuer: 'FreeCodeCamp',
      professor: '',
      description: ['HTML', 'CSS'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://courses.cognitiveclass.ai/certificates/e57bfb7f88a44359bee8b2f1fe82fd94',
      img: '/images/certificates/dltf.jpg',
      name: 'Deep Learning with TensorFlow',
      institute: 'Cognitive Class',
      issuer: 'IBM',
      professor: '',
      description: ['Python'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://courses.cognitiveclass.ai/certificates/261026b4c71042f880a1415cb6eb92ff',
      img: '/images/certificates/dlfund.jpg',
      name: 'Deep Learning Fundamentals',
      institute: 'Cognitive Class',
      issuer: 'IBM',
      professor: '',
      description: ['Python'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://courses.cognitiveclass.ai/certificates/04f14479b9c441248df1beced7644d83',
      img: '/images/certificates/da.jpg',
      name: 'Data Analysis with Python',
      institute: 'Cognitive Class',
      issuer: 'IBM',
      professor: '',
      description: ['Python'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://courses.cognitiveclass.ai/certificates/8127fd9abca148c4bc8344c34c9d6438',
      img: '/images/certificates/dataviz.jpg',
      name: 'Data Visualization with Python',
      institute: 'Cognitive Class',
      issuer: 'IBM',
      professor: '',
      description: ['Python'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://courses.cognitiveclass.ai/certificates/dc8e9f0115c945f6bd908b2376d6f43a',
      img: '/images/certificates/sql.jpg',
      name: 'SQL and Relational Databases',
      institute: 'Cognitive Class',
      issuer: 'IBM',
      professor: '',
      description: ['SQL'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.datacamp.com/statement-of-accomplishment/course/8668534e308738c8713ba0a1079a077958fe319d',
      img: '/images/certificates/git.jpg',
      name: 'Introduction to Git',
      institute: '',
      issuer: 'DataCamp',
      professor: '',
      description: ['Git'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.datacamp.com/statement-of-accomplishment/course/4ade713f3d70039debfe6c8c1a430f72c6d5649f',
      img: '/images/certificates/shell.jpg',
      name: 'Introduction to Shell',
      institute: '',
      issuer: 'DataCamp',
      professor: '',
      description: ['Shell'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.datacamp.com/statement-of-accomplishment/course/e50869d51065721fca64b1821866f0044e244786',
      img: '/images/certificates/py.jpg',
      name: 'Introduction to Python',
      issuer: 'DataCamp',
      professor: '',
      description: ['Python'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://du5jhqks4kn0y.cloudfront.net/5a74215418bd2c006c7aa953/certificates/5b7000499e2546006d40555d_cerf.pdf',
      img: '/images/certificates/ds.jpg',
      name: 'Data Structures',
      issuer: '',
      professor: '',
      description: ['Data Structures'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/learning-ecmascript-6',
      img: '/images/certificates/ECMAScript6.jpg',
      name: 'Learning ECMAScript 6',
      issuer: 'Linkedin',
      professor: '',
      description: ['Javascript'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/learning-react-native-2017',
      img: '/images/certificates/react_native.jpg',
      name: 'Learning React Native',
      institute: '',
      issuer: 'Linkedin',
      professor: '',
      description: ['React Native'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.datacamp.com/statement-of-accomplishment/course/ca02b713af7854206b0be3561d5b5f4a3e39c89b',
      img: '/images/certificates/spreadsheets.jpg',
      name: 'Introduction to SQL',
      issuer: 'DataCamp',
      professor: '',
      description: ['SQL'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://drive.google.com/file/d/1rtbMqWYD-O8ljcDBf-5Lnl9F1pRBqHxS/view?usp:sharing',
      img: '/images/certificates/amcat.jpg',
      name: 'Amcat Report',
      issuer: 'Amcat',
      professor: '',
      description: ['Aptitude'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.datacamp.com/statement-of-accomplishment/course/92b8db3bcfdcc3e466f1ab170f46c1b76b37bbdd',
      img: '/images/certificates/spreadsheets.jpg',
      name: 'Introduction to Spreadsheets',
      issuer: 'DataCamp',
      professor: '',
      description: ['Excel'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://courses.cognitiveclass.ai/certificates/07f3f8eb298c478d974c38aa459ef1f8',
      img: '/images/certificates/blockchain.jpg',
      name: 'Blockchain Essentials',
      institute: 'Cognitive Class',
      issuer: 'IBM',
      professor: 'developerWorks',
      description: ['Blockchain'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.datacamp.com/statement-of-accomplishment/course/543dd80cf86a37eec1cd98342d449d43f847c37e',
      img: '/images/certificates/r.jpg',
      name: 'Introduction to R',
      issuer: 'DataCamp',
      professor: '',
      description: ['R'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/express-essential-training',
      img: '/images/certificates/express_essential.jpg',
      name: 'Express Essential Training',
      institute: '',
      issuer: 'Linkedin',
      professor: 'Emmanuel Henri',
      description: ['Javascript', 'Express'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/docker-for-developers-2',
      img: '/images/certificates/docker_for_developers.jpg',
      name: 'Docker for Developers',
      institute: '',
      issuer: 'Linkedin',
      professor: 'Emmanuel Henri',
      description: ['Docker'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/node-js-real-time-web-with-socket-io',
      img: '/images/certificates/socket.jpg',
      name: 'Node.js: Real-Time Web with Socket.IO',
      institute: '',
      issuer: 'Linkedin',
      professor: 'Emmanuel Henri',
      description: ['Javascript', 'Node', 'Socket'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/advanced-sql-logical-query-processing',
      img: '/images/certificates/logical_sql.jpg',
      name: 'Advanced SQL – Logical Query Processing',
      issuer: 'Linkedin',
      professor: 'Ami Levin',
      description: ['SQL'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/oracle-database-12c-advanced-sql',
      img: '/images/certificates/adv_oracle_sql.jpg',
      name: 'Oracle Database 12c: Advanced SQL',
      issuer: 'Linkedin',
      professor: 'David Yahalom',
      description: ['Oracle', 'SQL'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.freecodecamp.org/certification/thebhushanmhatre/scientific-computing-with-python-v7',
      img: '/images/certificates/scientific-computing-with-python.jpg',
      name: 'Scientific Computing With Python Developer Certification',
      issuer: 'FreeCodeCamp',
      professor: '',
      description: ['Python'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/flask-essential-training',
      img: '/images/certificates/essential-flask.jpg',
      name: 'Flask Essential Training',
      issuer: 'Linkedin',
      professor: 'Nick Walter',
      description: ['Python'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/full-stack-web-development-with-flask',
      img: '/images/certificates/fullstack-flask.jpg',
      name: 'Full Stack Web Development with Flask',
      issuer: 'Linkedin',
      professor: 'Christian Hur',
      description: ['Python'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/python-decorators',
      img: '/images/certificates/python-decorators.jpg',
      name: 'Python Decorators',
      issuer: 'Linkedin',
      professor: 'Jonathan Fernandes',
      description: ['Python'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/EGYCA575BPZD',
      img: '/images/certificates/project-flask.jpg',
      name: 'Create Your First Web App with Python and Flask',
      issuer: 'Coursera',
      professor: 'Amit Yadav',
      description: ['Python', 'Flask'],
      visible: false,
      target: '_blank',
    },
    {
      href: 'https://www.coursera.org/account/accomplishments/certificate/3WWMX2WCRNC3',
      img: '/images/certificates/fin-mkt.jpg',
      name: 'Understanding Financial Markets',
      issuer: 'Coursera',
      institute: 'University of Geneva',
      professor: 'Michel Girardin',
      description: ['Finance'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'http://www.linkedin.com/learning/learning-django-2',
      img: '/images/certificates/learning_django.jpg',
      name: 'Learning Django',
      issuer: 'Linkedin',
      professor: 'Caleb Smith',
      description: ['Python', 'Django'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/advanced-sql-window-functions',
      img: '/images/certificates/adv-sql-window-functions.jpg',
      name: 'Advanced  SQL – Window Functions',
      issuer: 'Linkedin',
      professor: 'Ami Levin',
      description: ['SQL', 'Oracle SQL'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/advanced-sql-logical-query-processing-part-2',
      img: '/images/certificates/logical-sql-2.jpg',
      name: 'Advanced SQL: Logical Query Processing, Part 2',
      issuer: 'Linkedin',
      professor: 'Ami Levin',
      description: ['SQL', 'Oracle SQL'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/learning-docker-2018',
      img: '/images/certificates/learning-docker.jpg',
      name: 'Learning Docker',
      issuer: 'Linkedin',
      professor: 'Arthur Ulfeldt',
      description: ['Docker', 'Cloud'],
      visible: true,
      target: '_blank',
    },
    {
      href: 'https://www.linkedin.com/learning/learning-kubernetes',
      img: '/images/certificates/learning-kubernetes.jpg',
      name: 'Learning Kubernetes',
      issuer: 'Linkedin',
      professor: 'Karthik Gaekwad',
      description: ['Kubernetes', 'Cloud'],
      visible: true,
      target: '_blank',
    },
  ],
  contacts: [
    {
      href: 'https://www.linkedin.com/in/bhushanmhatre',
      name: 'linkedin',
    },
    {
      href: 'https://github.com/thebhushanmhatre',
      name: 'github',
    },
    {
      href: 'https://www.freecodecamp.org/thebhushanmhatre',
      name: 'freeCodeCamp',
    },
    {
      href: 'https://twitter.com/thebhushanmhatr',
      name: 'twitter',
    },
    {
      href: 'https://codepen.io/thebhushanmhatre/',
      name: 'codepen',
    },
    {
      href: 'https://www.hackerrank.com/bhushanmhatre',
      name: 'hackerrank',
    },
    {
      href: 'https://www.kaggle.com/thebhushanmhatre',
      name: 'kaggle',
    },
    {
      href: 'https://leetcode.com/bhushanmhatre/',
      name: 'kaggle',
    },
  ],
  education: [
    {
      href: 'https://en.wikipedia.org/wiki/Veermata_Jijabai_Technological_Institute',
      name: 'Veermata Jijabai Techological Institute',
      shortname: 'V.J.T.I.',
      img: 'images/vjti_logo.jpg',
      year: '2019',
      degree: 'B.Tech.',
    },
    {
      href: 'http://www.patkarvardecollege.edu.in/index.php',
      name: 'Patkar College of Science',
      shortname: 'Patkar College',
      img: 'images/patkar_logo.jpg',
      year: '2015',
      degree: 'Junior College (Science)',
    },
    {
      href: 'https://en.wikipedia.org/wiki/Saint_Francis_D%27Assisi_High_School',
      name: "St. Francis D'Assisi High School",
      shortname: 'S.F.H.S.',
      img: 'images/sfhs_logo.jpg',
      year: '2013',
      degree: 'School',
    },
  ],
  experience: [
    {
      company: 'MSCI Inc',
      from: '10-06-2019',
      to: 'Present',
    },
  ],
};
